version: '3.8'

services:
  mediaproxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        BUILD_TIME: ${BUILD_TIME}
        GIT_COMMIT: ${GIT_COMMIT}
    image: mediaproxy:${VERSION:-latest}
    container_name: mediaproxy
    restart: unless-stopped
    ports:
      - "${PORT:-57574}:57574"
    environment:
      - TZ=Asia/Shanghai
    command: ["-port", "57574", "-dns", "${DNS:-8.8.8.8}"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:57574/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mediaproxy-network
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mediaproxy-network:
    driver: bridge